#!/bin/bash

# skip oidc configuration
#exit 0

# Can't put this in the Dockerfile cause heimdall wasn't installed until 50-config runs
echo "**** install oidc plugin ****"
pushd /app/www
rm composer.lock
php /composer.phar require vizir/laravel-keycloak-web-guard --update-with-dependencies --with-all-dependencies 1> /tmp/one.txt 2> /tmp/two.txt
popd

# adjust laravel to use the oidc config
sed -i "s/            'driver' => 'session',/            'driver' => 'keycloak-web',/g" /app/www/config/auth.php
sed -i "s/            'driver' => 'eloquent',/            'driver' => 'keycloak-users',/g" /app/www/config/auth.php
sed -i 's/App\\User/Vizir\\KeycloakWebGuard\\Models\\KeycloakUser/g' /app/www/config/auth.php

#pushd /app/www
##php artisan cache:clear
##php artisan route:cache
#php artisan view:clear
#php artisan config:cache
#popd
